# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_group_by_input import RestaurantsGroupByInput  # noqa: E501

class TestRestaurantsGroupByInput(unittest.TestCase):
    """RestaurantsGroupByInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsGroupByInput:
        """Test RestaurantsGroupByInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsGroupByInput`
        """
        model = RestaurantsGroupByInput()  # noqa: E501
        if include_optional:
            return RestaurantsGroupByInput(
                avg = [
                    'rating'
                    ],
                count = [
                    '_all'
                    ],
                max = [
                    'about'
                    ],
                min = [
                    'about'
                    ],
                sum = [
                    'rating'
                    ],
                about = True,
                name = True,
                rating = True,
                reviews = True
            )
        else:
            return RestaurantsGroupByInput(
        )
        """

    def testRestaurantsGroupByInput(self):
        """Test RestaurantsGroupByInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
