# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_order_by_with_aggregation_input import RestaurantsOrderByWithAggregationInput  # noqa: E501

class TestRestaurantsOrderByWithAggregationInput(unittest.TestCase):
    """RestaurantsOrderByWithAggregationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsOrderByWithAggregationInput:
        """Test RestaurantsOrderByWithAggregationInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsOrderByWithAggregationInput`
        """
        model = RestaurantsOrderByWithAggregationInput()  # noqa: E501
        if include_optional:
            return RestaurantsOrderByWithAggregationInput(
                avg = neurelo.models.restaurants_avg_order_by_aggregate_input.restaurantsAvgOrderByAggregateInput(
                    rating = 'asc', ),
                count = neurelo.models.restaurants_count_order_by_aggregate_input.restaurantsCountOrderByAggregateInput(
                    about = 'asc', 
                    name = 'asc', 
                    rating = 'asc', 
                    reviews = 'asc', ),
                max = neurelo.models.restaurants_max_order_by_aggregate_input.restaurantsMaxOrderByAggregateInput(
                    about = 'asc', 
                    name = 'asc', 
                    rating = 'asc', ),
                min = neurelo.models.restaurants_min_order_by_aggregate_input.restaurantsMinOrderByAggregateInput(
                    about = 'asc', 
                    name = 'asc', 
                    rating = 'asc', ),
                sum = neurelo.models.restaurants_sum_order_by_aggregate_input.restaurantsSumOrderByAggregateInput(
                    rating = 'asc', ),
                about = 'asc',
                name = 'asc',
                rating = 'asc',
                reviews = 'asc'
            )
        else:
            return RestaurantsOrderByWithAggregationInput(
        )
        """

    def testRestaurantsOrderByWithAggregationInput(self):
        """Test RestaurantsOrderByWithAggregationInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
