# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_where_input import RestaurantsWhereInput  # noqa: E501

class TestRestaurantsWhereInput(unittest.TestCase):
    """RestaurantsWhereInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsWhereInput:
        """Test RestaurantsWhereInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsWhereInput`
        """
        model = RestaurantsWhereInput()  # noqa: E501
        if include_optional:
            return RestaurantsWhereInput(
                var_and = None,
                var_not = None,
                var_or = [
                    neurelo.models.restaurants_where_input.restaurantsWhereInput(
                        and = null, 
                        not = null, 
                        or = [
                            neurelo.models.restaurants_where_input.restaurantsWhereInput(
                                about = null, 
                                name = null, 
                                rating = null, 
                                reviews = neurelo.models.string_nullable_list_filter.StringNullableListFilter(
                                    eq = [
                                        ''
                                        ], 
                                    equals = [
                                        ''
                                        ], 
                                    has = '', 
                                    has_every = [
                                        ''
                                        ], 
                                    has_some = [
                                        ''
                                        ], 
                                    is_empty = True, ), )
                            ], 
                        about = null, 
                        name = null, 
                        rating = null, 
                        reviews = neurelo.models.string_nullable_list_filter.StringNullableListFilter(
                            has = '', 
                            is_empty = True, ), )
                    ],
                about = None,
                name = None,
                rating = None,
                reviews = neurelo.models.string_nullable_list_filter.StringNullableListFilter(
                    eq = [
                        ''
                        ], 
                    equals = [
                        ''
                        ], 
                    has = '', 
                    has_every = [
                        ''
                        ], 
                    has_some = [
                        ''
                        ], 
                    is_empty = True, )
            )
        else:
            return RestaurantsWhereInput(
        )
        """

    def testRestaurantsWhereInput(self):
        """Test RestaurantsWhereInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
