# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.sort_order import SortOrder  # noqa: E501

class TestSortOrder(unittest.TestCase):
    """SortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortOrder(self):
        """Test SortOrder"""
        # inst = SortOrder()

if __name__ == '__main__':
    unittest.main()
