# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_createreviews_input import RestaurantsCreatereviewsInput  # noqa: E501

class TestRestaurantsCreatereviewsInput(unittest.TestCase):
    """RestaurantsCreatereviewsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsCreatereviewsInput:
        """Test RestaurantsCreatereviewsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsCreatereviewsInput`
        """
        model = RestaurantsCreatereviewsInput()  # noqa: E501
        if include_optional:
            return RestaurantsCreatereviewsInput(
                set = [
                    ''
                    ]
            )
        else:
            return RestaurantsCreatereviewsInput(
                set = [
                    ''
                    ],
        )
        """

    def testRestaurantsCreatereviewsInput(self):
        """Test RestaurantsCreatereviewsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
