# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.create_many_restaurants201_response import CreateManyRestaurants201Response  # noqa: E501

class TestCreateManyRestaurants201Response(unittest.TestCase):
    """CreateManyRestaurants201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateManyRestaurants201Response:
        """Test CreateManyRestaurants201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateManyRestaurants201Response`
        """
        model = CreateManyRestaurants201Response()  # noqa: E501
        if include_optional:
            return CreateManyRestaurants201Response(
                data = neurelo.models.affected_rows_output.AffectedRowsOutput(
                    count = 56, )
            )
        else:
            return CreateManyRestaurants201Response(
                data = neurelo.models.affected_rows_output.AffectedRowsOutput(
                    count = 56, ),
        )
        """

    def testCreateManyRestaurants201Response(self):
        """Test CreateManyRestaurants201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
