# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.group_by_restaurants200_response import GroupByRestaurants200Response  # noqa: E501

class TestGroupByRestaurants200Response(unittest.TestCase):
    """GroupByRestaurants200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupByRestaurants200Response:
        """Test GroupByRestaurants200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupByRestaurants200Response`
        """
        model = GroupByRestaurants200Response()  # noqa: E501
        if include_optional:
            return GroupByRestaurants200Response(
                data = [
                    neurelo.models.restaurants_group_by_output_type.RestaurantsGroupByOutputType(
                        _avg = neurelo.models.restaurants_avg_aggregate_output_type.RestaurantsAvgAggregateOutputType(
                            rating = 1.337, ), 
                        _count = neurelo.models.restaurants_count_aggregate_output_type.RestaurantsCountAggregateOutputType(
                            _all = 56, 
                            about = 56, 
                            name = 56, 
                            rating = 56, 
                            reviews = 56, ), 
                        _max = neurelo.models.restaurants_max_aggregate_output_type.RestaurantsMaxAggregateOutputType(
                            about = '', 
                            name = '', 
                            rating = 1.337, ), 
                        _min = neurelo.models.restaurants_min_aggregate_output_type.RestaurantsMinAggregateOutputType(
                            about = '', 
                            name = '', 
                            rating = 1.337, ), 
                        _sum = neurelo.models.restaurants_sum_aggregate_output_type.RestaurantsSumAggregateOutputType(
                            rating = 1.337, ), 
                        about = '', 
                        name = '', 
                        rating = 1.337, 
                        reviews = [
                            ''
                            ], )
                    ]
            )
        else:
            return GroupByRestaurants200Response(
                data = [
                    neurelo.models.restaurants_group_by_output_type.RestaurantsGroupByOutputType(
                        _avg = neurelo.models.restaurants_avg_aggregate_output_type.RestaurantsAvgAggregateOutputType(
                            rating = 1.337, ), 
                        _count = neurelo.models.restaurants_count_aggregate_output_type.RestaurantsCountAggregateOutputType(
                            _all = 56, 
                            about = 56, 
                            name = 56, 
                            rating = 56, 
                            reviews = 56, ), 
                        _max = neurelo.models.restaurants_max_aggregate_output_type.RestaurantsMaxAggregateOutputType(
                            about = '', 
                            name = '', 
                            rating = 1.337, ), 
                        _min = neurelo.models.restaurants_min_aggregate_output_type.RestaurantsMinAggregateOutputType(
                            about = '', 
                            name = '', 
                            rating = 1.337, ), 
                        _sum = neurelo.models.restaurants_sum_aggregate_output_type.RestaurantsSumAggregateOutputType(
                            rating = 1.337, ), 
                        about = '', 
                        name = '', 
                        rating = 1.337, 
                        reviews = [
                            ''
                            ], )
                    ],
        )
        """

    def testGroupByRestaurants200Response(self):
        """Test GroupByRestaurants200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
