# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurelo.api.restaurants_api import RestaurantsApi  # noqa: E501


class TestRestaurantsApi(unittest.TestCase):
    """RestaurantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RestaurantsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_aggregate_by_restaurants(self) -> None:
        """Test case for aggregate_by_restaurants

        """
        pass

    def test_create_many_restaurants(self) -> None:
        """Test case for create_many_restaurants

        """
        pass

    def test_create_one_restaurants(self) -> None:
        """Test case for create_one_restaurants

        """
        pass

    def test_delete_restaurants(self) -> None:
        """Test case for delete_restaurants

        """
        pass

    def test_delete_restaurants_by_name(self) -> None:
        """Test case for delete_restaurants_by_name

        """
        pass

    def test_find_restaurants(self) -> None:
        """Test case for find_restaurants

        """
        pass

    def test_find_restaurants_by_name(self) -> None:
        """Test case for find_restaurants_by_name

        """
        pass

    def test_group_by_restaurants(self) -> None:
        """Test case for group_by_restaurants

        """
        pass

    def test_update_restaurants(self) -> None:
        """Test case for update_restaurants

        """
        pass

    def test_update_restaurants_by_name(self) -> None:
        """Test case for update_restaurants_by_name

        """
        pass


if __name__ == '__main__':
    unittest.main()
