# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_scalar_field_enum import RestaurantsScalarFieldEnum  # noqa: E501

class TestRestaurantsScalarFieldEnum(unittest.TestCase):
    """RestaurantsScalarFieldEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRestaurantsScalarFieldEnum(self):
        """Test RestaurantsScalarFieldEnum"""
        # inst = RestaurantsScalarFieldEnum()

if __name__ == '__main__':
    unittest.main()
