# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_group_by_output_type import RestaurantsGroupByOutputType  # noqa: E501

class TestRestaurantsGroupByOutputType(unittest.TestCase):
    """RestaurantsGroupByOutputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsGroupByOutputType:
        """Test RestaurantsGroupByOutputType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsGroupByOutputType`
        """
        model = RestaurantsGroupByOutputType()  # noqa: E501
        if include_optional:
            return RestaurantsGroupByOutputType(
                avg = neurelo.models.restaurants_avg_aggregate_output_type.RestaurantsAvgAggregateOutputType(
                    rating = 1.337, ),
                count = neurelo.models.restaurants_count_aggregate_output_type.RestaurantsCountAggregateOutputType(
                    _all = 56, 
                    about = 56, 
                    name = 56, 
                    rating = 56, 
                    reviews = 56, ),
                max = neurelo.models.restaurants_max_aggregate_output_type.RestaurantsMaxAggregateOutputType(
                    about = '', 
                    name = '', 
                    rating = 1.337, ),
                min = neurelo.models.restaurants_min_aggregate_output_type.RestaurantsMinAggregateOutputType(
                    about = '', 
                    name = '', 
                    rating = 1.337, ),
                sum = neurelo.models.restaurants_sum_aggregate_output_type.RestaurantsSumAggregateOutputType(
                    rating = 1.337, ),
                about = '',
                name = '',
                rating = 1.337,
                reviews = [
                    ''
                    ]
            )
        else:
            return RestaurantsGroupByOutputType(
        )
        """

    def testRestaurantsGroupByOutputType(self):
        """Test RestaurantsGroupByOutputType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
