# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_where_input_about import RestaurantsWhereInputAbout  # noqa: E501

class TestRestaurantsWhereInputAbout(unittest.TestCase):
    """RestaurantsWhereInputAbout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsWhereInputAbout:
        """Test RestaurantsWhereInputAbout
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsWhereInputAbout`
        """
        model = RestaurantsWhereInputAbout()  # noqa: E501
        if include_optional:
            return RestaurantsWhereInputAbout(
                contains = '',
                ends_with = '',
                eq = '',
                equals = '',
                gt = '',
                gte = '',
                var_in = [
                    ''
                    ],
                lt = '',
                lte = '',
                mode = 'default',
                var_not = None,
                not_in = [
                    ''
                    ],
                search = '',
                starts_with = ''
            )
        else:
            return RestaurantsWhereInputAbout(
        )
        """

    def testRestaurantsWhereInputAbout(self):
        """Test RestaurantsWhereInputAbout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
