# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.float_field_update_operations_input import FloatFieldUpdateOperationsInput  # noqa: E501

class TestFloatFieldUpdateOperationsInput(unittest.TestCase):
    """FloatFieldUpdateOperationsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FloatFieldUpdateOperationsInput:
        """Test FloatFieldUpdateOperationsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FloatFieldUpdateOperationsInput`
        """
        model = FloatFieldUpdateOperationsInput()  # noqa: E501
        if include_optional:
            return FloatFieldUpdateOperationsInput(
                decrement = 1.337,
                divide = 1.337,
                increment = 1.337,
                multiply = 1.337,
                set = 1.337
            )
        else:
            return FloatFieldUpdateOperationsInput(
        )
        """

    def testFloatFieldUpdateOperationsInput(self):
        """Test FloatFieldUpdateOperationsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
