# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.string_field_update_operations_input import StringFieldUpdateOperationsInput  # noqa: E501

class TestStringFieldUpdateOperationsInput(unittest.TestCase):
    """StringFieldUpdateOperationsInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringFieldUpdateOperationsInput:
        """Test StringFieldUpdateOperationsInput
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringFieldUpdateOperationsInput`
        """
        model = StringFieldUpdateOperationsInput()  # noqa: E501
        if include_optional:
            return StringFieldUpdateOperationsInput(
                set = ''
            )
        else:
            return StringFieldUpdateOperationsInput(
        )
        """

    def testStringFieldUpdateOperationsInput(self):
        """Test StringFieldUpdateOperationsInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
