# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.restaurants_where_input_rating import RestaurantsWhereInputRating  # noqa: E501

class TestRestaurantsWhereInputRating(unittest.TestCase):
    """RestaurantsWhereInputRating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestaurantsWhereInputRating:
        """Test RestaurantsWhereInputRating
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestaurantsWhereInputRating`
        """
        model = RestaurantsWhereInputRating()  # noqa: E501
        if include_optional:
            return RestaurantsWhereInputRating(
                eq = 1.337,
                equals = 1.337,
                gt = 1.337,
                gte = 1.337,
                var_in = [
                    1.337
                    ],
                lt = 1.337,
                lte = 1.337,
                var_not = None,
                not_in = [
                    1.337
                    ]
            )
        else:
            return RestaurantsWhereInputRating(
        )
        """

    def testRestaurantsWhereInputRating(self):
        """Test RestaurantsWhereInputRating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
