# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from neurelo.models.find_restaurants200_response import FindRestaurants200Response  # noqa: E501

class TestFindRestaurants200Response(unittest.TestCase):
    """FindRestaurants200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindRestaurants200Response:
        """Test FindRestaurants200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindRestaurants200Response`
        """
        model = FindRestaurants200Response()  # noqa: E501
        if include_optional:
            return FindRestaurants200Response(
                data = [
                    neurelo.models.restaurants.restaurants(
                        about = '', 
                        name = '', 
                        rating = 1.337, 
                        reviews = [
                            ''
                            ], )
                    ]
            )
        else:
            return FindRestaurants200Response(
                data = [
                    neurelo.models.restaurants.restaurants(
                        about = '', 
                        name = '', 
                        rating = 1.337, 
                        reviews = [
                            ''
                            ], )
                    ],
        )
        """

    def testFindRestaurants200Response(self):
        """Test FindRestaurants200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
