# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt

class FloatFieldUpdateOperationsInput(BaseModel):
    """
    FloatFieldUpdateOperationsInput
    """
    decrement: Optional[Union[StrictFloat, StrictInt]] = None
    divide: Optional[Union[StrictFloat, StrictInt]] = None
    increment: Optional[Union[StrictFloat, StrictInt]] = None
    multiply: Optional[Union[StrictFloat, StrictInt]] = None
    set: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["decrement", "divide", "increment", "multiply", "set"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FloatFieldUpdateOperationsInput:
        """Create an instance of FloatFieldUpdateOperationsInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FloatFieldUpdateOperationsInput:
        """Create an instance of FloatFieldUpdateOperationsInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FloatFieldUpdateOperationsInput.parse_obj(obj)

        _obj = FloatFieldUpdateOperationsInput.parse_obj({
            "decrement": obj.get("decrement"),
            "divide": obj.get("divide"),
            "increment": obj.get("increment"),
            "multiply": obj.get("multiply"),
            "set": obj.get("set")
        })
        return _obj


