# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, conlist
from neurelo.models.nested_float_filter import NestedFloatFilter
from neurelo.models.nested_int_filter import NestedIntFilter

class NestedFloatWithAggregatesFilter(BaseModel):
    """
    NestedFloatWithAggregatesFilter
    """
    avg: Optional[NestedFloatFilter] = Field(None, alias="_avg")
    count: Optional[NestedIntFilter] = Field(None, alias="_count")
    max: Optional[NestedFloatFilter] = Field(None, alias="_max")
    min: Optional[NestedFloatFilter] = Field(None, alias="_min")
    sum: Optional[NestedFloatFilter] = Field(None, alias="_sum")
    eq: Optional[Union[StrictFloat, StrictInt]] = None
    equals: Optional[Union[StrictFloat, StrictInt]] = None
    gt: Optional[Union[StrictFloat, StrictInt]] = None
    gte: Optional[Union[StrictFloat, StrictInt]] = None
    var_in: Optional[conlist(Union[StrictFloat, StrictInt])] = Field(None, alias="in")
    lt: Optional[Union[StrictFloat, StrictInt]] = None
    lte: Optional[Union[StrictFloat, StrictInt]] = None
    var_not: Optional[FloatWithAggregatesFilterNot] = Field(None, alias="not")
    not_in: Optional[conlist(Union[StrictFloat, StrictInt])] = Field(None, alias="notIn")
    __properties = ["_avg", "_count", "_max", "_min", "_sum", "eq", "equals", "gt", "gte", "in", "lt", "lte", "not", "notIn"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NestedFloatWithAggregatesFilter:
        """Create an instance of NestedFloatWithAggregatesFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of avg
        if self.avg:
            _dict['_avg'] = self.avg.to_dict()
        # override the default output from pydantic by calling `to_dict()` of count
        if self.count:
            _dict['_count'] = self.count.to_dict()
        # override the default output from pydantic by calling `to_dict()` of max
        if self.max:
            _dict['_max'] = self.max.to_dict()
        # override the default output from pydantic by calling `to_dict()` of min
        if self.min:
            _dict['_min'] = self.min.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sum
        if self.sum:
            _dict['_sum'] = self.sum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_not
        if self.var_not:
            _dict['not'] = self.var_not.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NestedFloatWithAggregatesFilter:
        """Create an instance of NestedFloatWithAggregatesFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NestedFloatWithAggregatesFilter.parse_obj(obj)

        _obj = NestedFloatWithAggregatesFilter.parse_obj({
            "avg": NestedFloatFilter.from_dict(obj.get("_avg")) if obj.get("_avg") is not None else None,
            "count": NestedIntFilter.from_dict(obj.get("_count")) if obj.get("_count") is not None else None,
            "max": NestedFloatFilter.from_dict(obj.get("_max")) if obj.get("_max") is not None else None,
            "min": NestedFloatFilter.from_dict(obj.get("_min")) if obj.get("_min") is not None else None,
            "sum": NestedFloatFilter.from_dict(obj.get("_sum")) if obj.get("_sum") is not None else None,
            "eq": obj.get("eq"),
            "equals": obj.get("equals"),
            "gt": obj.get("gt"),
            "gte": obj.get("gte"),
            "var_in": obj.get("in"),
            "lt": obj.get("lt"),
            "lte": obj.get("lte"),
            "var_not": FloatWithAggregatesFilterNot.from_dict(obj.get("not")) if obj.get("not") is not None else None,
            "not_in": obj.get("notIn")
        })
        return _obj

from neurelo.models.float_with_aggregates_filter_not import FloatWithAggregatesFilterNot
NestedFloatWithAggregatesFilter.update_forward_refs()

