# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class QueryMode(str, Enum):
    """
    QueryMode
    """

    """
    allowed enum values
    """
    DEFAULT = 'default'
    INSENSITIVE = 'insensitive'

    @classmethod
    def from_json(cls, json_str: str) -> QueryMode:
        """Create an instance of QueryMode from a JSON string"""
        return QueryMode(json.loads(json_str))


