# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from neurelo.models.restaurants_updatereviews_input_push import RestaurantsUpdatereviewsInputPush

class RestaurantsUpdatereviewsInput(BaseModel):
    """
    RestaurantsUpdatereviewsInput
    """
    push: Optional[RestaurantsUpdatereviewsInputPush] = None
    set: Optional[conlist(StrictStr)] = None
    __properties = ["push", "set"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RestaurantsUpdatereviewsInput:
        """Create an instance of RestaurantsUpdatereviewsInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of push
        if self.push:
            _dict['push'] = self.push.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RestaurantsUpdatereviewsInput:
        """Create an instance of RestaurantsUpdatereviewsInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RestaurantsUpdatereviewsInput.parse_obj(obj)

        _obj = RestaurantsUpdatereviewsInput.parse_obj({
            "push": RestaurantsUpdatereviewsInputPush.from_dict(obj.get("push")) if obj.get("push") is not None else None,
            "set": obj.get("set")
        })
        return _obj


