# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt

class RestaurantsSumAggregateOutputType(BaseModel):
    """
    RestaurantsSumAggregateOutputType
    """
    rating: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["rating"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RestaurantsSumAggregateOutputType:
        """Create an instance of RestaurantsSumAggregateOutputType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if rating (nullable) is None
        # and __fields_set__ contains the field
        if self.rating is None and "rating" in self.__fields_set__:
            _dict['rating'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RestaurantsSumAggregateOutputType:
        """Create an instance of RestaurantsSumAggregateOutputType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RestaurantsSumAggregateOutputType.parse_obj(obj)

        _obj = RestaurantsSumAggregateOutputType.parse_obj({
            "rating": obj.get("rating")
        })
        return _obj


