# coding: utf-8

"""
    Neurelo API Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist

class StringNullableListFilter(BaseModel):
    """
    StringNullableListFilter
    """
    eq: Optional[conlist(StrictStr)] = None
    equals: Optional[conlist(StrictStr)] = None
    has: Optional[StrictStr] = None
    has_every: Optional[conlist(StrictStr)] = Field(None, alias="hasEvery")
    has_some: Optional[conlist(StrictStr)] = Field(None, alias="hasSome")
    is_empty: Optional[StrictBool] = Field(None, alias="isEmpty")
    __properties = ["eq", "equals", "has", "hasEvery", "hasSome", "isEmpty"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StringNullableListFilter:
        """Create an instance of StringNullableListFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if has (nullable) is None
        # and __fields_set__ contains the field
        if self.has is None and "has" in self.__fields_set__:
            _dict['has'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StringNullableListFilter:
        """Create an instance of StringNullableListFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StringNullableListFilter.parse_obj(obj)

        _obj = StringNullableListFilter.parse_obj({
            "eq": obj.get("eq"),
            "equals": obj.get("equals"),
            "has": obj.get("has"),
            "has_every": obj.get("hasEvery"),
            "has_some": obj.get("hasSome"),
            "is_empty": obj.get("isEmpty")
        })
        return _obj


